
name: ContainerBuild

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: azure/docker-login@v1
              name: Docker Login
              with:
                login-server: ${{ secrets.MSLEARN_CONTAINER_REGISTRY }}
                username: ${{ secrets.MSLEARN_CONTAINER_REGISTRY_USERNAME }}
                password: ${{ secrets.MSLEARNCRSECRET }}

            - name: Push Docker image to Azure Container Registry    
              run: |
                docker build src -t ${{secrets.MSLEARN_CONTAINER_REGISTRY}}/aspnetcorecontainer:latest -t ${{ secrets.MSLEARN_CONTAINER_REGISTRY }}/aspnetcorecontainer:${{ github.sha }}
                docker push ${{ secrets.MSLEARN_CONTAINER_REGISTRY }}/aspnetcorecontainer:${{ github.sha }}
                docker push  ${{ secrets.MSLEARN_CONTAINER_REGISTRY }}/aspnetcorecontainer:latest